name: Deploy React to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "22"
      - name: Install Dependencies
        run: npm ci
      - name: Build
        run: npm run build
      - name: Upload artifact
        uses: actions/upload-artifact@v2 # Updated action to upload artifact
        with:
          name: build
          path: dist/. # Use the correct build output folder

  deploy:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: "https://${{ github.repository_owner }}.github.io/${{ github.event.repository.name }}/"
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v2 # Updated action to download artifact
        with:
          name: build
      - name: Setup Pages
        uses: actions/configure-pages@v5
      - name: Deploy
        uses: actions/deploy-pages@v4
